# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Enable swap on luks
  boot.initrd.luks.devices."luks-78400f5a-2814-4422-abef-c6b05b8d962c".device = "/dev/disk/by-uuid/78400f5a-2814-4422-abef-c6b05b8d962c";
  boot.initrd.luks.devices."luks-78400f5a-2814-4422-abef-c6b05b8d962c".keyFile = "/crypto_keyfile.bin";

  # Setup keyfile
  boot.initrd.secrets = {
    "/crypto_keyfile.bin" = null;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/178ebba4-850b-4c09-bb31-ad771ec0bd6c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c8d4dc12-8bec-410a-9014-b095a55b81f9".device = "/dev/disk/by-uuid/c8d4dc12-8bec-410a-9014-b095a55b81f9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1312-EE9B";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e3e1d66f-a9d9-43f1-8000-0aadacb361c0"; }
    ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
