return {

  {
    'catppuccin/nvim',
    tag = 'stable',
    name = 'catppuccin',
    priority = 1000,
    config = function()
      require'catppuccin'.setup({
        flavour = 'macchiato',
        transparent_background = true,
        integrations = {
          telescope = true,
          mason = true,
          -- harpoon = true,
          -- neotest = true,
        },
        color_overrides = {
          latte = { -- onedark
            rosewater = "#f5e0dc",
            flamingo = "#f2cdcd",
            pink = "#f5c2e7",
            mauve = "#c678dd",
            red = "#e06c75",
            maroon = "#eba0ac",
            peach = "#d19a66",
            yellow = "#e5c07b",
            green = "#98c379",
            teal = "#94e2d5",
            sky = "#56b5c2",
            sapphire = "#74c7ec",
            blue = "#61afef",
            lavender = "#b4befe",
            text = "#abb2bf",
            subtext1 = "#5c6370",
            subtext0 = "#5c6370",
            overlay2 = "#3b3f4c",
            overlay1 = "#3b3f4c",
            overlay0 = "#5c6370",
            surface2 = "#393f4a",
            surface1 = "#31353f",
            surface0 = "#31353f",
            base = "#282c34",
            mantle = "#21252b",
            crust = "#181a1f",
          },
          frappe = { -- gruvbox
            rosewater = "#ffc6be",
            flamingo = "#f2594b",
            pink = "#d3869b",
            mauve = "#b16286",
            red = "#cc241d",
            maroon = "#d65d0e",
            peach = "#fe8019",
            yellow = "#fabd2f",
            green = "#b8bb26",
            teal = "#8bba7f",
            sky = "#83a598",
            sapphire = "#8ec07c",
            blue = "#83a598",
            lavender = "#e2cca9",
            text = "#ebdbb2",
            subtext1 = "#e2cca9",
            subtext0 = "#e2cca9",
            overlay2 = "#928374",
            overlay1 = "#7c6f64",
            overlay0 = "#665c54",
            surface2 = "#504945",
            surface1 = "#3c3836",
            surface0 = "#32302f",
            base = "#282828",
            mantle = "#1d2021",
            crust = "#1b1b1b",
          },
        },
      })
      vim.cmd.colorscheme 'catppuccin'
    end
  },

}
